### ISSUE TITLE
move tigr81 inside an organization and move project type templates as repo in the organization

### ISSUE THREAD

**Issue by giuseppeambrosio97** [tigr81/tigr81#19]
- [x] move tigr81 inside an organization
- [x] move primereact template as a repo inside the organization
- [x] move fastapi template as a repo inside the organization
- [x] move poetry_pkg template as a repo inside the organization

design a process to make changes for a template:

- [x] create new version of a template with git tagging when merge on master

**Comment by DiTo97** [comment]
tigr81 organization ❤️
